### ISSUE TITLE
Coorporation with openhtmltopdf

### ISSUE THREAD

**Issue by m-a-t** [rjolly/flying-saucer#1]
Hi rjolly

https://github.com/danfickle/openhtmltopdf seems to be a pretty active continuation of flyingsaucer.

What is missing in openhtmltopdf is MathML support. If I read it right you managed to add MathML support to flyingsaucer. Could you share this great achievement and contribute it to openhtmltopdf? (I think openhtmltopdf can't use your code directly, because you have it GPL-licensed...)

Relevant issue: https://github.com/danfickle/openhtmltopdf/issues/161

**Comment by rjolly** [comment]
Answered in https://github.com/danfickle/openhtmltopdf/issues/161
